[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MMJMesh = "010ee2c9-7ff8-468a-b3f6-2ff8c4732c90"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[sources]
MMJMesh = {url = "https://github.com/matthiasbaitsch/mmjmesh.git"}
